name: Lambda Syncer
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/lambda-runner-binaries-syncer.yml
      - "modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/**"

jobs:
  build:
    uses: ./.github/workflows/lambda-template.yml
    with:
      working-directory: modules/runner-binaries-syncer/lambdas/runner-binaries-syncer
