name: Lambda Webhook
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/lambda-webhook.yml
      - "modules/webhook/lambdas/webhook/**"

jobs:
  build:
    uses: ./.github/workflows/lambda-template.yml
    with:
      working-directory: modules/webhook/lambdas/webhook
